/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(num *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Got the client request\n");
	printf("Add(%d, %d) is calling\n",argp->num1, argp->num2);
	result=argp->num1+argp->num2;

	return &result;
}
